// <auto-generated />
using System;
using DndCampaign.Modules.Missions.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DndCampaign.Modules.Missions.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(MissionsDbContext))]
    [Migration("20260823111334_InitialMissions")]
    partial class InitialMissions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("missions")
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DndCampaign.Modules.Missions.Domain.Missions.Mission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AuthorCharacterId")
                        .HasColumnType("uuid");

                    b.Property<string>("AuthorCharacterName")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<int>("AuthorType")
                        .HasColumnType("integer");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)");

                    b.Property<bool>("IsMain")
                        .HasColumnType("boolean");

                    b.Property<long>("SortSequence")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("SortSequence"));

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId");

                    b.HasIndex("CampaignId", "CreatedByUserId");

                    b.HasIndex("CampaignId", "IsMain")
                        .IsUnique()
                        .HasFilter("\"IsMain\" = TRUE");

                    b.HasIndex("CampaignId", "Status", "CreatedAt", "SortSequence");

                    b.ToTable("missions", "missions", t =>
                        {
                            t.HasCheckConstraint("CK_missions_author", "(\"AuthorType\" = 0 AND \"AuthorCharacterId\" IS NULL AND \"AuthorCharacterName\" IS NULL) OR (\"AuthorType\" = 1 AND \"AuthorCharacterId\" IS NOT NULL AND \"AuthorCharacterName\" IS NOT NULL)");

                            t.HasCheckConstraint("CK_missions_main_active", "NOT \"IsMain\" OR \"Status\" = 0");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
