import { ChangeDetectionStrategy, Component, OnInit, inject, signal } from '@angular/core';
import { FormControl, FormGroup, ReactiveFormsModule, Validators } from '@angular/forms';
import { ActivatedRoute, RouterLink } from '@angular/router';
import { finalize } from 'rxjs';
import { apiErrorMessage } from '@shared/http/problem-details';
import { AdventureChaptersClient } from './api/adventure-chapters.client';
import { AdventureChapter, AdventureChapterIndex } from './api/adventure-chapters.contracts';
@Component({ selector: 'dnd-adventure-chapters', imports: [ReactiveFormsModule, RouterLink], templateUrl: './adventure-chapters.page.html', styleUrl: './adventure-chapters.page.scss', changeDetection: ChangeDetectionStrategy.OnPush })
export class AdventureChaptersPage implements OnInit {
  private readonly client = inject(AdventureChaptersClient); private readonly route = inject(ActivatedRoute);
  readonly moduleId = this.route.snapshot.paramMap.get('moduleId') ?? ''; readonly campaignId = this.route.snapshot.paramMap.get('campaignId') ?? ''; readonly admin = !!this.moduleId;
  readonly index = signal<AdventureChapterIndex | null>(null); readonly selected = signal<AdventureChapter | null>(null); readonly loading = signal(true); readonly saving = signal(false); readonly error = signal<string | null>(null);
  readonly form = new FormGroup({ name: new FormControl('', { nonNullable: true, validators: [Validators.required, Validators.minLength(2), Validators.maxLength(120)] }), description: new FormControl('', { nonNullable: true, validators: [Validators.maxLength(20000)] }), rightsBasis: new FormControl('Contenido original del autor.', { nonNullable: true, validators: [Validators.required, Validators.minLength(3)] }) });
  ngOnInit() { this.load(); }
  load() { this.loading.set(true); this.error.set(null); const request = this.admin ? this.client.adminList(this.moduleId) : this.client.campaignList(this.campaignId); request.pipe(finalize(() => this.loading.set(false))).subscribe({ next: value => { this.index.set(value); if (!this.admin && value.chapters.length) this.open(value.chapters[0]); }, error: error => this.error.set(apiErrorMessage(error, this.admin ? 'No se han podido cargar los capítulos.' : 'No hay un módulo disponible o ya no tienes acceso.')) }); }
  edit(chapter: AdventureChapter | null) { this.selected.set(chapter); this.form.setValue({ name: chapter?.name ?? '', description: chapter?.description ?? '', rightsBasis: chapter?.provenance?.rightsBasis ?? 'Contenido original del autor.' }); }
  save() { if (this.form.invalid || this.saving()) return; const current = this.selected(); const input = { name: this.form.controls.name.value, description: this.form.controls.description.value, provenance: { originKind: 'Original' as const, rightsBasis: this.form.controls.rightsBasis.value }, expectedVersion: current?.version ?? undefined }; this.saving.set(true); const request = current ? this.client.update(this.moduleId, current.id, input) : this.client.create(this.moduleId, input); request.pipe(finalize(() => this.saving.set(false))).subscribe({ next: () => { this.edit(null); this.load(); }, error: error => this.error.set(apiErrorMessage(error, 'No se ha podido guardar. Recarga si el índice ha cambiado.')) }); }
  remove(chapter: AdventureChapter) { if (!confirm(`¿Eliminar el capítulo «${chapter.name}»?`)) return; this.client.delete(this.moduleId, chapter).subscribe({ next: () => this.load(), error: error => this.error.set(apiErrorMessage(error, 'No se ha podido eliminar.')) }); }
  move(chapter: AdventureChapter, offset: number) { const index = this.index(); if (!index) return; const ids = index.chapters.map(x => x.id); const from = ids.indexOf(chapter.id), to = from + offset; if (to < 0 || to >= ids.length) return; [ids[from], ids[to]] = [ids[to], ids[from]]; this.client.reorder(this.moduleId, index.indexVersion, ids).subscribe({ next: value => this.index.set(value), error: error => this.error.set(apiErrorMessage(error, 'El orden ha cambiado. Recarga para continuar.')) }); }
  open(chapter: AdventureChapter) { if (this.admin) { this.edit(chapter); return; } this.client.campaignGet(this.campaignId, chapter.id).subscribe({ next: value => this.selected.set(value), error: error => this.error.set(apiErrorMessage(error, 'No se ha podido abrir el capítulo.')) }); }
}
