// <auto-generated />
using System;
using DndCampaign.Modules.Combat.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DndCampaign.Modules.Combat.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CombatDbContext))]
    [Migration("20260823131803_EnemyGroupsAndEncounterDeletion")]
    partial class EnemyGroupsAndEncounterDeletion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("combat")
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DndCampaign.Modules.Combat.Domain.Encounters.Encounter", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ActivatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CurrentParticipantId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<int?>("Round")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<bool>("TiesResolved")
                        .HasColumnType("boolean");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId", "Status")
                        .IsUnique()
                        .HasFilter("\"Status\" = 1");

                    b.HasIndex("CampaignId", "Status", "CreatedAt");

                    b.ToTable("encounters", "combat", t =>
                        {
                            t.HasCheckConstraint("CK_encounters_lifecycle", "(\"Status\" = 0 AND \"Round\" IS NULL AND \"CurrentParticipantId\" IS NULL AND \"ActivatedAt\" IS NULL AND \"FinishedAt\" IS NULL) OR (\"Status\" = 1 AND \"Round\" >= 1 AND \"CurrentParticipantId\" IS NOT NULL AND \"ActivatedAt\" IS NOT NULL AND \"FinishedAt\" IS NULL) OR (\"Status\" = 2 AND \"Round\" >= 1 AND \"CurrentParticipantId\" IS NOT NULL AND \"ActivatedAt\" IS NOT NULL AND \"FinishedAt\" IS NOT NULL)");

                            t.HasCheckConstraint("CK_encounters_status", "\"Status\" BETWEEN 0 AND 2");

                            t.HasCheckConstraint("CK_encounters_version", "\"Version\" >= 1");
                        });
                });

            modelBuilder.Entity("DndCampaign.Modules.Combat.Domain.Encounters.EncounterParticipant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("ArmorClass")
                        .HasColumnType("integer");

                    b.Property<long>("CreatedOrder")
                        .HasColumnType("bigint");

                    b.Property<Guid>("EncounterId")
                        .HasColumnType("uuid");

                    b.Property<int>("InitiativeTotal")
                        .HasColumnType("integer");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<string>("NameSnapshot")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<int>("OrderPosition")
                        .HasColumnType("integer");

                    b.Property<Guid?>("SourceCharacterId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EncounterId", "CreatedOrder")
                        .IsUnique();

                    b.HasIndex("EncounterId", "OrderPosition")
                        .IsUnique();

                    b.HasIndex("EncounterId", "SourceCharacterId")
                        .IsUnique()
                        .HasFilter("\"SourceCharacterId\" IS NOT NULL");

                    b.ToTable("encounter_participants", "combat", t =>
                        {
                            t.HasCheckConstraint("CK_encounter_participants_armor", "\"ArmorClass\" BETWEEN 0 AND 40");

                            t.HasCheckConstraint("CK_encounter_participants_initiative", "\"InitiativeTotal\" BETWEEN -20 AND 30");

                            t.HasCheckConstraint("CK_encounter_participants_kind", "\"Kind\" BETWEEN 0 AND 1");

                            t.HasCheckConstraint("CK_encounter_participants_order", "\"OrderPosition\" >= 0 AND \"CreatedOrder\" >= 1");

                            t.HasCheckConstraint("CK_encounter_participants_shape", "(\"Kind\" = 0 AND \"SourceCharacterId\" IS NOT NULL) OR (\"Kind\" = 1 AND \"SourceCharacterId\" IS NULL)");
                        });
                });

            modelBuilder.Entity("DndCampaign.Modules.Combat.Domain.Encounters.EnemyGroupMember", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("CurrentHitPoints")
                        .HasColumnType("integer");

                    b.Property<int>("MaximumHitPoints")
                        .HasColumnType("integer");

                    b.Property<int>("Ordinal")
                        .HasColumnType("integer");

                    b.Property<Guid>("ParticipantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ParticipantId", "Ordinal")
                        .IsUnique();

                    b.ToTable("enemy_group_members", "combat", t =>
                        {
                            t.HasCheckConstraint("CK_enemy_group_members_hit_points", "\"MaximumHitPoints\" BETWEEN 1 AND 100000 AND \"CurrentHitPoints\" BETWEEN 0 AND \"MaximumHitPoints\"");

                            t.HasCheckConstraint("CK_enemy_group_members_ordinal", "\"Ordinal\" BETWEEN 1 AND 100");
                        });
                });

            modelBuilder.Entity("DndCampaign.Modules.Combat.Domain.Encounters.EncounterParticipant", b =>
                {
                    b.HasOne("DndCampaign.Modules.Combat.Domain.Encounters.Encounter", null)
                        .WithMany("Participants")
                        .HasForeignKey("EncounterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DndCampaign.Modules.Combat.Domain.Encounters.EnemyGroupMember", b =>
                {
                    b.HasOne("DndCampaign.Modules.Combat.Domain.Encounters.EncounterParticipant", null)
                        .WithMany("EnemyMembers")
                        .HasForeignKey("ParticipantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DndCampaign.Modules.Combat.Domain.Encounters.Encounter", b =>
                {
                    b.Navigation("Participants");
                });

            modelBuilder.Entity("DndCampaign.Modules.Combat.Domain.Encounters.EncounterParticipant", b =>
                {
                    b.Navigation("EnemyMembers");
                });
#pragma warning restore 612, 618
        }
    }
}
