// <auto-generated />
using System;
using DndCampaign.Modules.AdventureCatalog.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DndCampaign.Modules.AdventureCatalog.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AdventureCatalogDbContext))]
    partial class AdventureCatalogDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("adventure_catalog")
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DndCampaign.Modules.AdventureCatalog.Domain.AdventureModules.AdventureModule", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<long>("ChaptersVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)");

                    b.Property<Guid>("LastModifiedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique();

                    b.HasIndex("UpdatedAt", "Id");

                    b.ToTable("adventure_modules", "adventure_catalog", t =>
                        {
                            t.HasCheckConstraint("CK_adventure_modules_cover_shape", "(\"CoverObjectKey\" IS NULL AND \"CoverContentType\" IS NULL AND \"CoverSizeBytes\" IS NULL) OR (\"CoverObjectKey\" IS NOT NULL AND \"CoverContentType\" IS NOT NULL AND \"CoverSizeBytes\" BETWEEN 1 AND 10485760)");

                            t.HasCheckConstraint("CK_adventure_modules_version", "\"Version\" >= 1");
                        });
                });

            modelBuilder.Entity("DndCampaign.Modules.AdventureCatalog.Domain.Chapters.AdventureChapter", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(20000)
                        .HasColumnType("character varying(20000)");

                    b.Property<Guid>("LastModifiedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ModuleId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ModuleId", "Position")
                        .IsUnique();

                    b.ToTable("adventure_chapters", "adventure_catalog", t =>
                        {
                            t.HasCheckConstraint("CK_adventure_chapters_position", "\"Position\" >= 1");

                            t.HasCheckConstraint("CK_adventure_chapters_version", "\"Version\" >= 1");
                        });
                });

            modelBuilder.Entity("DndCampaign.Modules.AdventureCatalog.Domain.Maps.AdventureMap", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(10000)
                        .HasColumnType("character varying(10000)");

                    b.Property<Guid>("LastModifiedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ModuleId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ModuleId", "UpdatedAt");

                    b.ToTable("adventure_maps", "adventure_catalog", t =>
                        {
                            t.HasCheckConstraint("CK_adventure_maps_version", "\"Version\" >= 1");
                        });
                });

            modelBuilder.Entity("DndCampaign.Modules.AdventureCatalog.Domain.Maps.AdventureMapChapter", b =>
                {
                    b.Property<Guid>("MapId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChapterId")
                        .HasColumnType("uuid");

                    b.HasKey("MapId", "ChapterId");

                    b.HasIndex("ChapterId");

                    b.ToTable("adventure_map_chapters", "adventure_catalog");
                });

            modelBuilder.Entity("DndCampaign.Modules.AdventureCatalog.Domain.AdventureModules.AdventureModule", b =>
                {
                    b.OwnsOne("DndCampaign.Modules.AdventureCatalog.Domain.AdventureModules.EditorialProvenance", "CoverProvenance", b1 =>
                        {
                            b1.Property<Guid>("AdventureModuleId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Attribution")
                                .HasMaxLength(2000)
                                .HasColumnType("character varying(2000)")
                                .HasColumnName("CoverAttribution");

                            b1.Property<int>("OriginKind")
                                .HasColumnType("integer")
                                .HasColumnName("CoverOriginKind");

                            b1.Property<string>("RightsBasis")
                                .IsRequired()
                                .HasMaxLength(2000)
                                .HasColumnType("character varying(2000)")
                                .HasColumnName("CoverRightsBasis");

                            b1.Property<string>("SourceReference")
                                .HasMaxLength(2000)
                                .HasColumnType("character varying(2000)")
                                .HasColumnName("CoverSourceReference");

                            b1.Property<DateTimeOffset>("VerifiedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("CoverVerifiedAt");

                            b1.Property<Guid>("VerifiedByUserId")
                                .HasColumnType("uuid")
                                .HasColumnName("CoverVerifiedByUserId");

                            b1.HasKey("AdventureModuleId");

                            b1.ToTable("adventure_modules", "adventure_catalog");

                            b1.WithOwner()
                                .HasForeignKey("AdventureModuleId");
                        });

                    b.OwnsOne("DndCampaign.Modules.AdventureCatalog.Domain.AdventureModules.EditorialProvenance", "TextProvenance", b1 =>
                        {
                            b1.Property<Guid>("AdventureModuleId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Attribution")
                                .HasMaxLength(2000)
                                .HasColumnType("character varying(2000)")
                                .HasColumnName("TextAttribution");

                            b1.Property<int>("OriginKind")
                                .HasColumnType("integer")
                                .HasColumnName("TextOriginKind");

                            b1.Property<string>("RightsBasis")
                                .IsRequired()
                                .HasMaxLength(2000)
                                .HasColumnType("character varying(2000)")
                                .HasColumnName("TextRightsBasis");

                            b1.Property<string>("SourceReference")
                                .HasMaxLength(2000)
                                .HasColumnType("character varying(2000)")
                                .HasColumnName("TextSourceReference");

                            b1.Property<DateTimeOffset>("VerifiedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("TextVerifiedAt");

                            b1.Property<Guid>("VerifiedByUserId")
                                .HasColumnType("uuid")
                                .HasColumnName("TextVerifiedByUserId");

                            b1.HasKey("AdventureModuleId");

                            b1.ToTable("adventure_modules", "adventure_catalog");

                            b1.WithOwner()
                                .HasForeignKey("AdventureModuleId");
                        });

                    b.OwnsOne("DndCampaign.Modules.AdventureCatalog.Domain.AdventureModules.AdventureModuleCover", "Cover", b1 =>
                        {
                            b1.Property<Guid>("AdventureModuleId")
                                .HasColumnType("uuid");

                            b1.Property<string>("ContentType")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("character varying(32)")
                                .HasColumnName("CoverContentType");

                            b1.Property<string>("ObjectKey")
                                .IsRequired()
                                .HasMaxLength(512)
                                .HasColumnType("character varying(512)")
                                .HasColumnName("CoverObjectKey");

                            b1.Property<long>("SizeBytes")
                                .HasColumnType("bigint")
                                .HasColumnName("CoverSizeBytes");

                            b1.HasKey("AdventureModuleId");

                            b1.ToTable("adventure_modules", "adventure_catalog");

                            b1.WithOwner()
                                .HasForeignKey("AdventureModuleId");
                        });

                    b.Navigation("Cover");

                    b.Navigation("CoverProvenance");

                    b.Navigation("TextProvenance")
                        .IsRequired();
                });

            modelBuilder.Entity("DndCampaign.Modules.AdventureCatalog.Domain.Chapters.AdventureChapter", b =>
                {
                    b.HasOne("DndCampaign.Modules.AdventureCatalog.Domain.AdventureModules.AdventureModule", null)
                        .WithMany()
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("DndCampaign.Modules.AdventureCatalog.Domain.AdventureModules.EditorialProvenance", "Provenance", b1 =>
                        {
                            b1.Property<Guid>("AdventureChapterId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Attribution")
                                .HasMaxLength(2000)
                                .HasColumnType("character varying(2000)")
                                .HasColumnName("ChapterAttribution");

                            b1.Property<int>("OriginKind")
                                .HasColumnType("integer")
                                .HasColumnName("ChapterOriginKind");

                            b1.Property<string>("RightsBasis")
                                .IsRequired()
                                .HasMaxLength(2000)
                                .HasColumnType("character varying(2000)")
                                .HasColumnName("ChapterRightsBasis");

                            b1.Property<string>("SourceReference")
                                .HasMaxLength(2000)
                                .HasColumnType("character varying(2000)")
                                .HasColumnName("ChapterSourceReference");

                            b1.Property<DateTimeOffset>("VerifiedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("ChapterVerifiedAt");

                            b1.Property<Guid>("VerifiedByUserId")
                                .HasColumnType("uuid")
                                .HasColumnName("ChapterVerifiedByUserId");

                            b1.HasKey("AdventureChapterId");

                            b1.ToTable("adventure_chapters", "adventure_catalog");

                            b1.WithOwner()
                                .HasForeignKey("AdventureChapterId");
                        });

                    b.Navigation("Provenance")
                        .IsRequired();
                });

            modelBuilder.Entity("DndCampaign.Modules.AdventureCatalog.Domain.Maps.AdventureMap", b =>
                {
                    b.HasOne("DndCampaign.Modules.AdventureCatalog.Domain.AdventureModules.AdventureModule", null)
                        .WithMany()
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("DndCampaign.Modules.AdventureCatalog.Domain.AdventureModules.EditorialProvenance", "ImageProvenance", b1 =>
                        {
                            b1.Property<Guid>("AdventureMapId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Attribution")
                                .HasMaxLength(2000)
                                .HasColumnType("character varying(2000)")
                                .HasColumnName("ImageAttribution");

                            b1.Property<int>("OriginKind")
                                .HasColumnType("integer")
                                .HasColumnName("ImageOriginKind");

                            b1.Property<string>("RightsBasis")
                                .IsRequired()
                                .HasMaxLength(2000)
                                .HasColumnType("character varying(2000)")
                                .HasColumnName("ImageRightsBasis");

                            b1.Property<string>("SourceReference")
                                .HasMaxLength(2000)
                                .HasColumnType("character varying(2000)")
                                .HasColumnName("ImageSourceReference");

                            b1.Property<DateTimeOffset>("VerifiedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("ImageVerifiedAt");

                            b1.Property<Guid>("VerifiedByUserId")
                                .HasColumnType("uuid")
                                .HasColumnName("ImageVerifiedByUserId");

                            b1.HasKey("AdventureMapId");

                            b1.ToTable("adventure_maps", "adventure_catalog");

                            b1.WithOwner()
                                .HasForeignKey("AdventureMapId");
                        });

                    b.OwnsOne("DndCampaign.Modules.AdventureCatalog.Domain.Maps.AdventureMapImage", "Image", b1 =>
                        {
                            b1.Property<Guid>("AdventureMapId")
                                .HasColumnType("uuid");

                            b1.Property<string>("ContentType")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("character varying(32)")
                                .HasColumnName("ImageContentType");

                            b1.Property<int>("Height")
                                .HasColumnType("integer")
                                .HasColumnName("ImageHeight");

                            b1.Property<string>("ObjectKey")
                                .IsRequired()
                                .HasMaxLength(512)
                                .HasColumnType("character varying(512)")
                                .HasColumnName("ImageObjectKey");

                            b1.Property<long>("SizeBytes")
                                .HasColumnType("bigint")
                                .HasColumnName("ImageSizeBytes");

                            b1.Property<int>("Width")
                                .HasColumnType("integer")
                                .HasColumnName("ImageWidth");

                            b1.HasKey("AdventureMapId");

                            b1.ToTable("adventure_maps", "adventure_catalog");

                            b1.WithOwner()
                                .HasForeignKey("AdventureMapId");
                        });

                    b.Navigation("Image");

                    b.Navigation("ImageProvenance");
                });

            modelBuilder.Entity("DndCampaign.Modules.AdventureCatalog.Domain.Maps.AdventureMapChapter", b =>
                {
                    b.HasOne("DndCampaign.Modules.AdventureCatalog.Domain.Chapters.AdventureChapter", null)
                        .WithMany()
                        .HasForeignKey("ChapterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DndCampaign.Modules.AdventureCatalog.Domain.Maps.AdventureMap", null)
                        .WithMany("Chapters")
                        .HasForeignKey("MapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DndCampaign.Modules.AdventureCatalog.Domain.Maps.AdventureMap", b =>
                {
                    b.Navigation("Chapters");
                });
#pragma warning restore 612, 618
        }
    }
}
